name: meter_reader_flutter
description: "app for meter reading and printing for DapCWD"

publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.2
  
  # UI Components
  flutter_svg: ^2.0.17
  
  # Database
  sqflite: ^2.4.1
  path_provider: ^2.1.5 
  path: ^1.9.0
  
  # File Operations
  file_picker: ^9.0.2
  image: ^4.0.17
  
  # Utilities
  intl: ^0.20.2
  
  # Printing
  esc_pos_utils_plus: ^2.0.4
  blue_thermal_printer:
    path: ./local_packages/blue_thermal_printer




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  sqflite_common_ffi: ^2.3.2
  flutter_native_splash: ^2.4.6 
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/icons/

flutter_native_splash:
  color: "#ffffff"
  image: assets\icons\512x512logo.png
  android: true
  ios: true
  web: false

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icons/512x512logo.png
  remove_alpha_ios: true