name: meter_reader_flutter
description: "A new Flutter project."

publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.1.2
  flutter_svg: ^2.0.17

  file_picker: ^8.3.1
  sqflite: ^2.4.1
  path_provider: ^2.1.5 
  path: ^1.9.0
  permission_handler: ^11.4.0
  external_path: ^2.2.0
  
  cupertino_icons: ^1.0.8
  esc_pos_utils: ^1.1.0
  intl: ^0.20.2
  http: ^1.3.0
  blue_thermal_printer:
    path: ./local_packages/blue_thermal_printer




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  sqflite_common_ffi: ^2.3.2

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
